package main

import (
	"fmt"
	"os"
	"os/exec"
	"strconv"
	"strings"

	"github.com/magefile/mage/mg"
	"github.com/magefile/mage/sh"
)

// Fmt contains targets for formatting code.
type Fmt mg.Namespace

// GoFix runs `go fix` iteratively until it reaches a fixed point.
func (Fmt) GoFix() error {
	color("Run go fix...")
	maxIter, err := strconv.Atoi(gofixMaxIterations)
	if err != nil {
		maxIter = 5
	}
	flags := strings.Fields(gofixFlags)
	for n := range maxIter {
		args := append([]string{"fix"}, flags...)
		args = append(args, "./...")
		cmd := exec.Command("go", args...)
		out, _ := cmd.CombinedOutput()
		output := string(out)
		fmt.Print(output)
		if !strings.Contains(output, "files updated") {
			break
		}
		if n == maxIter-1 {
			return fmt.Errorf("go fix did not converge after %d iterations", maxIter)
		}
		color("Re-running go fix...")
	}
	return nil
}

// Imports formats imports using gci.
func (Fmt) Imports() error {
	color("Formatting imports...")
	return devtool("gci", "write", "--skip-generated", "-s", "standard", "-s", "default", "./*")
}

// Yaml formats YAML files.
func (Fmt) Yaml() error {
	color("Formatting YAML files...")
	return devtool("yamlfmt", "-conf", ".github/.yamlfmt", ".")
}

// Goimports runs goimports on all non-generated Go files.
func (Fmt) Goimports() error {
	color("Run goimports for all files...")
	files, err := findGoFiles()
	if err != nil {
		return err
	}
	// Filter out generated files.
	var ungenerated []string
	for _, f := range files {
		content, err := os.ReadFile(f)
		if err != nil {
			continue
		}
		if !strings.Contains(string(content), "Code generated by") || !strings.Contains(string(content), "DO NOT EDIT.") {
			ungenerated = append(ungenerated, f)
		}
	}
	args := append([]string{"-w"}, ungenerated...)
	return goTool("goimports", args...)
}

// All runs all formatters.
func (f Fmt) All() {
	mg.Deps(f.GoFix, f.Imports, f.Yaml)
}

// ParallelizeTests adds t.Parallel() to tests.
func (Fmt) ParallelizeTests() error {
	color("Add t.Parallel() to tests...")
	args := append([]string{"run", "./cmd/tools/parallelize"}, integrationTestDirs...)
	return sh.RunV("go", args...)
}
